sudo: required
services:
  - docker

before_install:
  - docker build -t bhavani/multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bhavani/multi-test npm test

after_success:
  - docker build -t bpurvam/multi-client ./client
  - docker build -t bpurvam/multi-nginx ./nginx
  - docker build -t bpurvam/multi-server ./server
  - docker build -t bpurvam/multi-worker ./worker
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push docker.io/bpurvam/multi-client
  - docker push docker.io/bpurvam/multi-nginx
  - docker push docker.io/bpurvam/multi-server
  - docker push docker.io/bpurvam/multi-worker
